/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as GenesisDistrictRouteImport } from './routes/genesis-district'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as EliasRouteImport } from './routes/elias'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as AgentFleetRouteImport } from './routes/agent-fleet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as MarketplaceSellRouteImport } from './routes/marketplace.sell'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalImprintRouteImport } from './routes/legal.imprint'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as DropsSlugRouteImport } from './routes/drops.$slug'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DotwellKnownFarcasterDotjsonRouteImport } from './routes/[.]well-known/farcaster[.]json'
import { Route as ApiX402PremiumRouteImport } from './routes/api/x402/premium'
import { Route as ApiEliasInboundRouteImport } from './routes/api/elias/inbound'
import { Route as ApiAgentsStatusRouteImport } from './routes/api/agents/status'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const GenesisDistrictRoute = GenesisDistrictRouteImport.update({
  id: '/genesis-district',
  path: '/genesis-district',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const EliasRoute = EliasRouteImport.update({
  id: '/elias',
  path: '/elias',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFleetRoute = AgentFleetRouteImport.update({
  id: '/agent-fleet',
  path: '/agent-fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSellRoute = MarketplaceSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const DropsSlugRoute = DropsSlugRouteImport.update({
  id: '/drops/$slug',
  path: '/drops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownFarcasterDotjsonRoute =
  DotwellKnownFarcasterDotjsonRouteImport.update({
    id: '/.well-known/farcaster.json',
    path: '/.well-known/farcaster.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiX402PremiumRoute = ApiX402PremiumRouteImport.update({
  id: '/api/x402/premium',
  path: '/api/x402/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEliasInboundRoute = ApiEliasInboundRouteImport.update({
  id: '/api/elias/inbound',
  path: '/api/elias/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsStatusRoute = ApiAgentsStatusRouteImport.update({
  id: '/api/agents/status',
  path: '/api/agents/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent-fleet': typeof AgentFleetRoute
  '/campaign': typeof CampaignRoute
  '/collections': typeof CollectionsRoute
  '/elias': typeof EliasRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/genesis-district': typeof GenesisDistrictRoute
  '/investors': typeof InvestorsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mission': typeof MissionRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/p/$slug': typeof PSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/agents/status': typeof ApiAgentsStatusRoute
  '/api/elias/inbound': typeof ApiEliasInboundRoute
  '/api/x402/premium': typeof ApiX402PremiumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent-fleet': typeof AgentFleetRoute
  '/campaign': typeof CampaignRoute
  '/collections': typeof CollectionsRoute
  '/elias': typeof EliasRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/genesis-district': typeof GenesisDistrictRoute
  '/investors': typeof InvestorsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRouteWithChildren
  '/mission': typeof MissionRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/p/$slug': typeof PSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/agents/status': typeof ApiAgentsStatusRoute
  '/api/elias/inbound': typeof ApiEliasInboundRoute
  '/api/x402/premium': typeof ApiX402PremiumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent-fleet': typeof AgentFleetRoute
  '/campaign': typeof CampaignRoute
  '/collections': typeof CollectionsRoute
  '/elias': typeof EliasRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/genesis-district': typeof GenesisDistrictRoute
  '/investors': typeof InvestorsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mission': typeof MissionRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/p/$slug': typeof PSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/agents/status': typeof ApiAgentsStatusRoute
  '/api/elias/inbound': typeof ApiEliasInboundRoute
  '/api/x402/premium': typeof ApiX402PremiumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent-fleet'
    | '/campaign'
    | '/collections'
    | '/elias'
    | '/experiences'
    | '/faq'
    | '/genesis-district'
    | '/investors'
    | '/leaderboard'
    | '/legal'
    | '/marketplace'
    | '/mission'
    | '/play'
    | '/profile'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/.well-known/farcaster.json'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/drops/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$listingId'
    | '/marketplace/sell'
    | '/p/$slug'
    | '/sitemap/xml'
    | '/blog/'
    | '/docs/'
    | '/marketplace/'
    | '/api/agents/status'
    | '/api/elias/inbound'
    | '/api/x402/premium'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agent-fleet'
    | '/campaign'
    | '/collections'
    | '/elias'
    | '/experiences'
    | '/faq'
    | '/genesis-district'
    | '/investors'
    | '/leaderboard'
    | '/legal'
    | '/mission'
    | '/play'
    | '/profile'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/.well-known/farcaster.json'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/drops/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$listingId'
    | '/marketplace/sell'
    | '/p/$slug'
    | '/sitemap/xml'
    | '/blog'
    | '/docs'
    | '/marketplace'
    | '/api/agents/status'
    | '/api/elias/inbound'
    | '/api/x402/premium'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent-fleet'
    | '/campaign'
    | '/collections'
    | '/elias'
    | '/experiences'
    | '/faq'
    | '/genesis-district'
    | '/investors'
    | '/leaderboard'
    | '/legal'
    | '/marketplace'
    | '/mission'
    | '/play'
    | '/profile'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/.well-known/farcaster.json'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/drops/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$listingId'
    | '/marketplace/sell'
    | '/p/$slug'
    | '/sitemap/xml'
    | '/blog/'
    | '/docs/'
    | '/marketplace/'
    | '/api/agents/status'
    | '/api/elias/inbound'
    | '/api/x402/premium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentFleetRoute: typeof AgentFleetRoute
  CampaignRoute: typeof CampaignRoute
  CollectionsRoute: typeof CollectionsRoute
  EliasRoute: typeof EliasRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  GenesisDistrictRoute: typeof GenesisDistrictRoute
  InvestorsRoute: typeof InvestorsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LegalRoute: typeof LegalRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MissionRoute: typeof MissionRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  DotwellKnownFarcasterDotjsonRoute: typeof DotwellKnownFarcasterDotjsonRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DropsSlugRoute: typeof DropsSlugRoute
  PSlugRoute: typeof PSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAgentsStatusRoute: typeof ApiAgentsStatusRoute
  ApiEliasInboundRoute: typeof ApiEliasInboundRoute
  ApiX402PremiumRoute: typeof ApiX402PremiumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genesis-district': {
      id: '/genesis-district'
      path: '/genesis-district'
      fullPath: '/genesis-district'
      preLoaderRoute: typeof GenesisDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elias': {
      id: '/elias'
      path: '/elias'
      fullPath: '/elias'
      preLoaderRoute: typeof EliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-fleet': {
      id: '/agent-fleet'
      path: '/agent-fleet'
      fullPath: '/agent-fleet'
      preLoaderRoute: typeof AgentFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/sell': {
      id: '/marketplace/sell'
      path: '/sell'
      fullPath: '/marketplace/sell'
      preLoaderRoute: typeof MarketplaceSellRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/drops/$slug': {
      id: '/drops/$slug'
      path: '/drops/$slug'
      fullPath: '/drops/$slug'
      preLoaderRoute: typeof DropsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/farcaster.json': {
      id: '/.well-known/farcaster.json'
      path: '/.well-known/farcaster.json'
      fullPath: '/.well-known/farcaster.json'
      preLoaderRoute: typeof DotwellKnownFarcasterDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/premium': {
      id: '/api/x402/premium'
      path: '/api/x402/premium'
      fullPath: '/api/x402/premium'
      preLoaderRoute: typeof ApiX402PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elias/inbound': {
      id: '/api/elias/inbound'
      path: '/api/elias/inbound'
      fullPath: '/api/elias/inbound'
      preLoaderRoute: typeof ApiEliasInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/status': {
      id: '/api/agents/status'
      path: '/api/agents/status'
      fullPath: '/api/agents/status'
      preLoaderRoute: typeof ApiAgentsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  MarketplaceSellRoute: typeof MarketplaceSellRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  MarketplaceSellRoute: MarketplaceSellRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentFleetRoute: AgentFleetRoute,
  CampaignRoute: CampaignRoute,
  CollectionsRoute: CollectionsRoute,
  EliasRoute: EliasRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  GenesisDistrictRoute: GenesisDistrictRoute,
  InvestorsRoute: InvestorsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LegalRoute: LegalRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MissionRoute: MissionRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  DotwellKnownFarcasterDotjsonRoute: DotwellKnownFarcasterDotjsonRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsSlugRoute: DocsSlugRoute,
  DropsSlugRoute: DropsSlugRoute,
  PSlugRoute: PSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAgentsStatusRoute: ApiAgentsStatusRoute,
  ApiEliasInboundRoute: ApiEliasInboundRoute,
  ApiX402PremiumRoute: ApiX402PremiumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
