import type { OpsAgentRecord } from "../types.js";
import type { LedgerInsert } from "../ledger-pg.js";
import {
  createClients,
  readMintsToday,
  resolveCampaign,
} from "../chain-ags.js";
import { contractsEnv, chainId, baseRpcUrl } from "../env.js";

export async function runNewsWriterTick(agent: OpsAgentRecord): Promise<LedgerInsert> {
  const env = contractsEnv();
  const cid = chainId();
  const rpc = baseRpcUrl();
  const { publicClient } = createClients(cid, rpc);
  const campaign = resolveCampaign(env, cid);
  let mintsToday = "n/a";
  if (campaign) {
    try {
      const n = await readMintsToday(publicClient, campaign);
      mintsToday = n.toString();
    } catch {
      mintsToday = "error";
    }
  }
  const title = `Agent digest — ${new Date().toISOString().slice(0, 10)}`;
  const body = [
    `## On-chain snapshot`,
    ``,
    `- **AgentShareCampaign mints today:** ${mintsToday}`,
    `- **Chain:** Base (${cid})`,
    ``,
    `_Draft generated by \`${agent.id}\`. Publish via Strapi when reviewed._`,
  ].join("\n");

  const token = process.env.STRAPI_API_TOKEN?.trim();
  let strapiStatus = "skipped_no_token";
  if (token && process.env.STRAPI_URL?.trim()) {
    try {
      const base = process.env.STRAPI_URL!.replace(/\/$/, "");
      const res = await fetch(`${base}/api/articles`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          data: {
            title,
            slug: `agent-digest-${Date.now()}`,
            excerpt: "Auto draft — agent fleet",
            content: body,
            publishedAt: null,
          },
        }),
      });
      strapiStatus = res.ok ? "draft_created" : `http_${res.status}`;
    } catch (e) {
      strapiStatus = `error:${e instanceof Error ? e.message : String(e)}`;
    }
  }

  return {
    agentId: agent.id,
    action: "ops.news_writer_digest",
    params: { title, strapiStatus, mintsToday },
    dryRun: false,
    status: "ok",
    txHash: null,
    costUsd: null,
  };
}
