/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PresaleRouteImport } from './routes/presale'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GenesisDistrictRouteImport } from './routes/genesis-district'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as EliasRouteImport } from './routes/elias'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ChatbaseRouteImport } from './routes/chatbase'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as AgentFleetRouteImport } from './routes/agent-fleet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as SignalIndexRouteImport } from './routes/signal/index'
import { Route as PlacesIndexRouteImport } from './routes/places/index'
import { Route as PassIndexRouteImport } from './routes/pass/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as ForestIndexRouteImport } from './routes/forest/index'
import { Route as EarthIndexRouteImport } from './routes/earth/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as WalletPacksRouteImport } from './routes/wallet/packs'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as SelfAgentidRouteImport } from './routes/self.agentid'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as NNameRouteImport } from './routes/n/$name'
import { Route as MarketplaceSellRouteImport } from './routes/marketplace.sell'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalImprintRouteImport } from './routes/legal.imprint'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as IdNameRouteImport } from './routes/id/$name'
import { Route as ForestQuestsRouteImport } from './routes/forest/quests'
import { Route as DropsArtRouteImport } from './routes/drops/art'
import { Route as DropsSlugRouteImport } from './routes/drops.$slug'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as R0gAgentidRouteImport } from './routes/0g.agentid'
import { Route as DotwellKnownFarcasterDotjsonRouteImport } from './routes/[.]well-known/farcaster[.]json'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known/agent[.]json'
import { Route as ApiX402PremiumRouteImport } from './routes/api/x402/premium'
import { Route as ApiWorldWalletVerifyRouteImport } from './routes/api/world/wallet-verify'
import { Route as ApiWorldWalletNonceRouteImport } from './routes/api/world/wallet-nonce'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWalletSyncRouteImport } from './routes/api/wallet/sync'
import { Route as ApiRewardsSummaryRouteImport } from './routes/api/rewards/summary'
import { Route as ApiPulseMetricsRouteImport } from './routes/api/pulse/metrics'
import { Route as ApiPulseFeedRouteImport } from './routes/api/pulse/feed'
import { Route as ApiPlatformWaitlistRouteImport } from './routes/api/platform/waitlist'
import { Route as ApiPlatformSiweNonceRouteImport } from './routes/api/platform/siwe-nonce'
import { Route as ApiPlatformOnboardingCompleteRouteImport } from './routes/api/platform/onboarding-complete'
import { Route as ApiPlatformAnalyticsRouteImport } from './routes/api/platform/analytics'
import { Route as ApiMemberMeRouteImport } from './routes/api/member/me'
import { Route as ApiMarketingXPostRouteImport } from './routes/api/marketing/x-post'
import { Route as ApiIdentityVerifyNameRouteImport } from './routes/api/identity/verify-name'
import { Route as ApiIdentityResolveRouteImport } from './routes/api/identity/resolve'
import { Route as ApiEliasInboundRouteImport } from './routes/api/elias/inbound'
import { Route as ApiComplianceEligibilityRouteImport } from './routes/api/compliance/eligibility'
import { Route as ApiAgentsStatusRouteImport } from './routes/api/agents/status'
import { Route as ApiActivityLogRouteImport } from './routes/api/activity/log'
import { Route as ApiWalletPacksCheckoutRouteImport } from './routes/api/wallet/packs/checkout'
import { Route as ApiPulseIngestManualRouteImport } from './routes/api/pulse/ingest/manual'
import { Route as ApiPulseDigestDayIdRouteImport } from './routes/api/pulse/digest/$dayId'
import { Route as ApiPulseAttestationLatestRouteImport } from './routes/api/pulse/attestation/latest'
import { Route as ApiPulseFeedIdCommentsRouteImport } from './routes/api/pulse/feed/$id/comments'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PresaleRoute = PresaleRouteImport.update({
  id: '/presale',
  path: '/presale',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GenesisDistrictRoute = GenesisDistrictRouteImport.update({
  id: '/genesis-district',
  path: '/genesis-district',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const EliasRoute = EliasRouteImport.update({
  id: '/elias',
  path: '/elias',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbaseRoute = ChatbaseRouteImport.update({
  id: '/chatbase',
  path: '/chatbase',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFleetRoute = AgentFleetRouteImport.update({
  id: '/agent-fleet',
  path: '/agent-fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalIndexRoute = SignalIndexRouteImport.update({
  id: '/signal/',
  path: '/signal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassIndexRoute = PassIndexRouteImport.update({
  id: '/pass/',
  path: '/pass/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ForestIndexRoute = ForestIndexRouteImport.update({
  id: '/forest/',
  path: '/forest/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthIndexRoute = EarthIndexRouteImport.update({
  id: '/earth/',
  path: '/earth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletPacksRoute = WalletPacksRouteImport.update({
  id: '/wallet/packs',
  path: '/wallet/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfAgentidRoute = SelfAgentidRouteImport.update({
  id: '/self/agentid',
  path: '/self/agentid',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NNameRoute = NNameRouteImport.update({
  id: '/n/$name',
  path: '/n/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSellRoute = MarketplaceSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const IdNameRoute = IdNameRouteImport.update({
  id: '/id/$name',
  path: '/id/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ForestQuestsRoute = ForestQuestsRouteImport.update({
  id: '/forest/quests',
  path: '/forest/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsArtRoute = DropsArtRouteImport.update({
  id: '/drops/art',
  path: '/drops/art',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsSlugRoute = DropsSlugRouteImport.update({
  id: '/drops/$slug',
  path: '/drops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const R0gAgentidRoute = R0gAgentidRouteImport.update({
  id: '/0g/agentid',
  path: '/0g/agentid',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownFarcasterDotjsonRoute =
  DotwellKnownFarcasterDotjsonRouteImport.update({
    id: '/.well-known/farcaster.json',
    path: '/.well-known/farcaster.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiX402PremiumRoute = ApiX402PremiumRouteImport.update({
  id: '/api/x402/premium',
  path: '/api/x402/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldWalletVerifyRoute = ApiWorldWalletVerifyRouteImport.update({
  id: '/api/world/wallet-verify',
  path: '/api/world/wallet-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldWalletNonceRoute = ApiWorldWalletNonceRouteImport.update({
  id: '/api/world/wallet-nonce',
  path: '/api/world/wallet-nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletSyncRoute = ApiWalletSyncRouteImport.update({
  id: '/api/wallet/sync',
  path: '/api/wallet/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewardsSummaryRoute = ApiRewardsSummaryRouteImport.update({
  id: '/api/rewards/summary',
  path: '/api/rewards/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseMetricsRoute = ApiPulseMetricsRouteImport.update({
  id: '/api/pulse/metrics',
  path: '/api/pulse/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseFeedRoute = ApiPulseFeedRouteImport.update({
  id: '/api/pulse/feed',
  path: '/api/pulse/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformWaitlistRoute = ApiPlatformWaitlistRouteImport.update({
  id: '/api/platform/waitlist',
  path: '/api/platform/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformSiweNonceRoute = ApiPlatformSiweNonceRouteImport.update({
  id: '/api/platform/siwe-nonce',
  path: '/api/platform/siwe-nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformOnboardingCompleteRoute =
  ApiPlatformOnboardingCompleteRouteImport.update({
    id: '/api/platform/onboarding-complete',
    path: '/api/platform/onboarding-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlatformAnalyticsRoute = ApiPlatformAnalyticsRouteImport.update({
  id: '/api/platform/analytics',
  path: '/api/platform/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemberMeRoute = ApiMemberMeRouteImport.update({
  id: '/api/member/me',
  path: '/api/member/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingXPostRoute = ApiMarketingXPostRouteImport.update({
  id: '/api/marketing/x-post',
  path: '/api/marketing/x-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdentityVerifyNameRoute = ApiIdentityVerifyNameRouteImport.update({
  id: '/api/identity/verify-name',
  path: '/api/identity/verify-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdentityResolveRoute = ApiIdentityResolveRouteImport.update({
  id: '/api/identity/resolve',
  path: '/api/identity/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEliasInboundRoute = ApiEliasInboundRouteImport.update({
  id: '/api/elias/inbound',
  path: '/api/elias/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceEligibilityRoute =
  ApiComplianceEligibilityRouteImport.update({
    id: '/api/compliance/eligibility',
    path: '/api/compliance/eligibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentsStatusRoute = ApiAgentsStatusRouteImport.update({
  id: '/api/agents/status',
  path: '/api/agents/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityLogRoute = ApiActivityLogRouteImport.update({
  id: '/api/activity/log',
  path: '/api/activity/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletPacksCheckoutRoute = ApiWalletPacksCheckoutRouteImport.update({
  id: '/api/wallet/packs/checkout',
  path: '/api/wallet/packs/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseIngestManualRoute = ApiPulseIngestManualRouteImport.update({
  id: '/api/pulse/ingest/manual',
  path: '/api/pulse/ingest/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseDigestDayIdRoute = ApiPulseDigestDayIdRouteImport.update({
  id: '/api/pulse/digest/$dayId',
  path: '/api/pulse/digest/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseAttestationLatestRoute =
  ApiPulseAttestationLatestRouteImport.update({
    id: '/api/pulse/attestation/latest',
    path: '/api/pulse/attestation/latest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPulseFeedIdCommentsRoute = ApiPulseFeedIdCommentsRouteImport.update({
  id: '/$id/comments',
  path: '/$id/comments',
  getParentRoute: () => ApiPulseFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent-fleet': typeof AgentFleetRoute
  '/campaign': typeof CampaignRoute
  '/chatbase': typeof ChatbaseRoute
  '/collections': typeof CollectionsRoute
  '/elias': typeof EliasRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/genesis-district': typeof GenesisDistrictRoute
  '/guide': typeof GuideRoute
  '/investors': typeof InvestorsRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mission': typeof MissionRoute
  '/play': typeof PlayRoute
  '/presale': typeof PresaleRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/0g/agentid': typeof R0gAgentidRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/drops/art': typeof DropsArtRoute
  '/forest/quests': typeof ForestQuestsRoute
  '/id/$name': typeof IdNameRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/n/$name': typeof NNameRoute
  '/p/$slug': typeof PSlugRoute
  '/self/agentid': typeof SelfAgentidRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/wallet/packs': typeof WalletPacksRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/earth/': typeof EarthIndexRoute
  '/forest/': typeof ForestIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/pass/': typeof PassIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/signal/': typeof SignalIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/api/activity/log': typeof ApiActivityLogRoute
  '/api/agents/status': typeof ApiAgentsStatusRoute
  '/api/compliance/eligibility': typeof ApiComplianceEligibilityRoute
  '/api/elias/inbound': typeof ApiEliasInboundRoute
  '/api/identity/resolve': typeof ApiIdentityResolveRoute
  '/api/identity/verify-name': typeof ApiIdentityVerifyNameRoute
  '/api/marketing/x-post': typeof ApiMarketingXPostRoute
  '/api/member/me': typeof ApiMemberMeRoute
  '/api/platform/analytics': typeof ApiPlatformAnalyticsRoute
  '/api/platform/onboarding-complete': typeof ApiPlatformOnboardingCompleteRoute
  '/api/platform/siwe-nonce': typeof ApiPlatformSiweNonceRoute
  '/api/platform/waitlist': typeof ApiPlatformWaitlistRoute
  '/api/pulse/feed': typeof ApiPulseFeedRouteWithChildren
  '/api/pulse/metrics': typeof ApiPulseMetricsRoute
  '/api/rewards/summary': typeof ApiRewardsSummaryRoute
  '/api/wallet/sync': typeof ApiWalletSyncRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/world/wallet-nonce': typeof ApiWorldWalletNonceRoute
  '/api/world/wallet-verify': typeof ApiWorldWalletVerifyRoute
  '/api/x402/premium': typeof ApiX402PremiumRoute
  '/api/pulse/attestation/latest': typeof ApiPulseAttestationLatestRoute
  '/api/pulse/digest/$dayId': typeof ApiPulseDigestDayIdRoute
  '/api/pulse/ingest/manual': typeof ApiPulseIngestManualRoute
  '/api/wallet/packs/checkout': typeof ApiWalletPacksCheckoutRoute
  '/api/pulse/feed/$id/comments': typeof ApiPulseFeedIdCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent-fleet': typeof AgentFleetRoute
  '/campaign': typeof CampaignRoute
  '/chatbase': typeof ChatbaseRoute
  '/collections': typeof CollectionsRoute
  '/elias': typeof EliasRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/genesis-district': typeof GenesisDistrictRoute
  '/guide': typeof GuideRoute
  '/investors': typeof InvestorsRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRouteWithChildren
  '/mission': typeof MissionRoute
  '/play': typeof PlayRoute
  '/presale': typeof PresaleRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/0g/agentid': typeof R0gAgentidRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/drops/art': typeof DropsArtRoute
  '/forest/quests': typeof ForestQuestsRoute
  '/id/$name': typeof IdNameRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/n/$name': typeof NNameRoute
  '/p/$slug': typeof PSlugRoute
  '/self/agentid': typeof SelfAgentidRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/wallet/packs': typeof WalletPacksRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/earth': typeof EarthIndexRoute
  '/forest': typeof ForestIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/pass': typeof PassIndexRoute
  '/places': typeof PlacesIndexRoute
  '/signal': typeof SignalIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/welcome': typeof WelcomeIndexRoute
  '/api/activity/log': typeof ApiActivityLogRoute
  '/api/agents/status': typeof ApiAgentsStatusRoute
  '/api/compliance/eligibility': typeof ApiComplianceEligibilityRoute
  '/api/elias/inbound': typeof ApiEliasInboundRoute
  '/api/identity/resolve': typeof ApiIdentityResolveRoute
  '/api/identity/verify-name': typeof ApiIdentityVerifyNameRoute
  '/api/marketing/x-post': typeof ApiMarketingXPostRoute
  '/api/member/me': typeof ApiMemberMeRoute
  '/api/platform/analytics': typeof ApiPlatformAnalyticsRoute
  '/api/platform/onboarding-complete': typeof ApiPlatformOnboardingCompleteRoute
  '/api/platform/siwe-nonce': typeof ApiPlatformSiweNonceRoute
  '/api/platform/waitlist': typeof ApiPlatformWaitlistRoute
  '/api/pulse/feed': typeof ApiPulseFeedRouteWithChildren
  '/api/pulse/metrics': typeof ApiPulseMetricsRoute
  '/api/rewards/summary': typeof ApiRewardsSummaryRoute
  '/api/wallet/sync': typeof ApiWalletSyncRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/world/wallet-nonce': typeof ApiWorldWalletNonceRoute
  '/api/world/wallet-verify': typeof ApiWorldWalletVerifyRoute
  '/api/x402/premium': typeof ApiX402PremiumRoute
  '/api/pulse/attestation/latest': typeof ApiPulseAttestationLatestRoute
  '/api/pulse/digest/$dayId': typeof ApiPulseDigestDayIdRoute
  '/api/pulse/ingest/manual': typeof ApiPulseIngestManualRoute
  '/api/wallet/packs/checkout': typeof ApiWalletPacksCheckoutRoute
  '/api/pulse/feed/$id/comments': typeof ApiPulseFeedIdCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent-fleet': typeof AgentFleetRoute
  '/campaign': typeof CampaignRoute
  '/chatbase': typeof ChatbaseRoute
  '/collections': typeof CollectionsRoute
  '/elias': typeof EliasRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/genesis-district': typeof GenesisDistrictRoute
  '/guide': typeof GuideRoute
  '/investors': typeof InvestorsRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mission': typeof MissionRoute
  '/play': typeof PlayRoute
  '/presale': typeof PresaleRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/0g/agentid': typeof R0gAgentidRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/drops/art': typeof DropsArtRoute
  '/forest/quests': typeof ForestQuestsRoute
  '/id/$name': typeof IdNameRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/n/$name': typeof NNameRoute
  '/p/$slug': typeof PSlugRoute
  '/self/agentid': typeof SelfAgentidRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/wallet/packs': typeof WalletPacksRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/earth/': typeof EarthIndexRoute
  '/forest/': typeof ForestIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/pass/': typeof PassIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/signal/': typeof SignalIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/api/activity/log': typeof ApiActivityLogRoute
  '/api/agents/status': typeof ApiAgentsStatusRoute
  '/api/compliance/eligibility': typeof ApiComplianceEligibilityRoute
  '/api/elias/inbound': typeof ApiEliasInboundRoute
  '/api/identity/resolve': typeof ApiIdentityResolveRoute
  '/api/identity/verify-name': typeof ApiIdentityVerifyNameRoute
  '/api/marketing/x-post': typeof ApiMarketingXPostRoute
  '/api/member/me': typeof ApiMemberMeRoute
  '/api/platform/analytics': typeof ApiPlatformAnalyticsRoute
  '/api/platform/onboarding-complete': typeof ApiPlatformOnboardingCompleteRoute
  '/api/platform/siwe-nonce': typeof ApiPlatformSiweNonceRoute
  '/api/platform/waitlist': typeof ApiPlatformWaitlistRoute
  '/api/pulse/feed': typeof ApiPulseFeedRouteWithChildren
  '/api/pulse/metrics': typeof ApiPulseMetricsRoute
  '/api/rewards/summary': typeof ApiRewardsSummaryRoute
  '/api/wallet/sync': typeof ApiWalletSyncRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/world/wallet-nonce': typeof ApiWorldWalletNonceRoute
  '/api/world/wallet-verify': typeof ApiWorldWalletVerifyRoute
  '/api/x402/premium': typeof ApiX402PremiumRoute
  '/api/pulse/attestation/latest': typeof ApiPulseAttestationLatestRoute
  '/api/pulse/digest/$dayId': typeof ApiPulseDigestDayIdRoute
  '/api/pulse/ingest/manual': typeof ApiPulseIngestManualRoute
  '/api/wallet/packs/checkout': typeof ApiWalletPacksCheckoutRoute
  '/api/pulse/feed/$id/comments': typeof ApiPulseFeedIdCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent-fleet'
    | '/campaign'
    | '/chatbase'
    | '/collections'
    | '/elias'
    | '/experiences'
    | '/faq'
    | '/genesis-district'
    | '/guide'
    | '/investors'
    | '/join'
    | '/leaderboard'
    | '/legal'
    | '/marketplace'
    | '/mission'
    | '/play'
    | '/presale'
    | '/profile'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/.well-known/agent.json'
    | '/.well-known/farcaster.json'
    | '/0g/agentid'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/drops/$slug'
    | '/drops/art'
    | '/forest/quests'
    | '/id/$name'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$listingId'
    | '/marketplace/sell'
    | '/n/$name'
    | '/p/$slug'
    | '/self/agentid'
    | '/sitemap/xml'
    | '/wallet/packs'
    | '/blog/'
    | '/docs/'
    | '/earth/'
    | '/forest/'
    | '/marketplace/'
    | '/pass/'
    | '/places/'
    | '/signal/'
    | '/wallet/'
    | '/welcome/'
    | '/api/activity/log'
    | '/api/agents/status'
    | '/api/compliance/eligibility'
    | '/api/elias/inbound'
    | '/api/identity/resolve'
    | '/api/identity/verify-name'
    | '/api/marketing/x-post'
    | '/api/member/me'
    | '/api/platform/analytics'
    | '/api/platform/onboarding-complete'
    | '/api/platform/siwe-nonce'
    | '/api/platform/waitlist'
    | '/api/pulse/feed'
    | '/api/pulse/metrics'
    | '/api/rewards/summary'
    | '/api/wallet/sync'
    | '/api/webhooks/stripe'
    | '/api/world/wallet-nonce'
    | '/api/world/wallet-verify'
    | '/api/x402/premium'
    | '/api/pulse/attestation/latest'
    | '/api/pulse/digest/$dayId'
    | '/api/pulse/ingest/manual'
    | '/api/wallet/packs/checkout'
    | '/api/pulse/feed/$id/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agent-fleet'
    | '/campaign'
    | '/chatbase'
    | '/collections'
    | '/elias'
    | '/experiences'
    | '/faq'
    | '/genesis-district'
    | '/guide'
    | '/investors'
    | '/join'
    | '/leaderboard'
    | '/legal'
    | '/mission'
    | '/play'
    | '/presale'
    | '/profile'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/.well-known/agent.json'
    | '/.well-known/farcaster.json'
    | '/0g/agentid'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/drops/$slug'
    | '/drops/art'
    | '/forest/quests'
    | '/id/$name'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$listingId'
    | '/marketplace/sell'
    | '/n/$name'
    | '/p/$slug'
    | '/self/agentid'
    | '/sitemap/xml'
    | '/wallet/packs'
    | '/blog'
    | '/docs'
    | '/earth'
    | '/forest'
    | '/marketplace'
    | '/pass'
    | '/places'
    | '/signal'
    | '/wallet'
    | '/welcome'
    | '/api/activity/log'
    | '/api/agents/status'
    | '/api/compliance/eligibility'
    | '/api/elias/inbound'
    | '/api/identity/resolve'
    | '/api/identity/verify-name'
    | '/api/marketing/x-post'
    | '/api/member/me'
    | '/api/platform/analytics'
    | '/api/platform/onboarding-complete'
    | '/api/platform/siwe-nonce'
    | '/api/platform/waitlist'
    | '/api/pulse/feed'
    | '/api/pulse/metrics'
    | '/api/rewards/summary'
    | '/api/wallet/sync'
    | '/api/webhooks/stripe'
    | '/api/world/wallet-nonce'
    | '/api/world/wallet-verify'
    | '/api/x402/premium'
    | '/api/pulse/attestation/latest'
    | '/api/pulse/digest/$dayId'
    | '/api/pulse/ingest/manual'
    | '/api/wallet/packs/checkout'
    | '/api/pulse/feed/$id/comments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent-fleet'
    | '/campaign'
    | '/chatbase'
    | '/collections'
    | '/elias'
    | '/experiences'
    | '/faq'
    | '/genesis-district'
    | '/guide'
    | '/investors'
    | '/join'
    | '/leaderboard'
    | '/legal'
    | '/marketplace'
    | '/mission'
    | '/play'
    | '/presale'
    | '/profile'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/.well-known/agent.json'
    | '/.well-known/farcaster.json'
    | '/0g/agentid'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/drops/$slug'
    | '/drops/art'
    | '/forest/quests'
    | '/id/$name'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$listingId'
    | '/marketplace/sell'
    | '/n/$name'
    | '/p/$slug'
    | '/self/agentid'
    | '/sitemap/xml'
    | '/wallet/packs'
    | '/blog/'
    | '/docs/'
    | '/earth/'
    | '/forest/'
    | '/marketplace/'
    | '/pass/'
    | '/places/'
    | '/signal/'
    | '/wallet/'
    | '/welcome/'
    | '/api/activity/log'
    | '/api/agents/status'
    | '/api/compliance/eligibility'
    | '/api/elias/inbound'
    | '/api/identity/resolve'
    | '/api/identity/verify-name'
    | '/api/marketing/x-post'
    | '/api/member/me'
    | '/api/platform/analytics'
    | '/api/platform/onboarding-complete'
    | '/api/platform/siwe-nonce'
    | '/api/platform/waitlist'
    | '/api/pulse/feed'
    | '/api/pulse/metrics'
    | '/api/rewards/summary'
    | '/api/wallet/sync'
    | '/api/webhooks/stripe'
    | '/api/world/wallet-nonce'
    | '/api/world/wallet-verify'
    | '/api/x402/premium'
    | '/api/pulse/attestation/latest'
    | '/api/pulse/digest/$dayId'
    | '/api/pulse/ingest/manual'
    | '/api/wallet/packs/checkout'
    | '/api/pulse/feed/$id/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentFleetRoute: typeof AgentFleetRoute
  CampaignRoute: typeof CampaignRoute
  ChatbaseRoute: typeof ChatbaseRoute
  CollectionsRoute: typeof CollectionsRoute
  EliasRoute: typeof EliasRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  GenesisDistrictRoute: typeof GenesisDistrictRoute
  GuideRoute: typeof GuideRoute
  InvestorsRoute: typeof InvestorsRoute
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LegalRoute: typeof LegalRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MissionRoute: typeof MissionRoute
  PlayRoute: typeof PlayRoute
  PresaleRoute: typeof PresaleRoute
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownFarcasterDotjsonRoute: typeof DotwellKnownFarcasterDotjsonRoute
  R0gAgentidRoute: typeof R0gAgentidRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DropsSlugRoute: typeof DropsSlugRoute
  DropsArtRoute: typeof DropsArtRoute
  ForestQuestsRoute: typeof ForestQuestsRoute
  IdNameRoute: typeof IdNameRoute
  NNameRoute: typeof NNameRoute
  PSlugRoute: typeof PSlugRoute
  SelfAgentidRoute: typeof SelfAgentidRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  WalletPacksRoute: typeof WalletPacksRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  EarthIndexRoute: typeof EarthIndexRoute
  ForestIndexRoute: typeof ForestIndexRoute
  PassIndexRoute: typeof PassIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  SignalIndexRoute: typeof SignalIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
  ApiActivityLogRoute: typeof ApiActivityLogRoute
  ApiAgentsStatusRoute: typeof ApiAgentsStatusRoute
  ApiComplianceEligibilityRoute: typeof ApiComplianceEligibilityRoute
  ApiEliasInboundRoute: typeof ApiEliasInboundRoute
  ApiIdentityResolveRoute: typeof ApiIdentityResolveRoute
  ApiIdentityVerifyNameRoute: typeof ApiIdentityVerifyNameRoute
  ApiMarketingXPostRoute: typeof ApiMarketingXPostRoute
  ApiMemberMeRoute: typeof ApiMemberMeRoute
  ApiPlatformAnalyticsRoute: typeof ApiPlatformAnalyticsRoute
  ApiPlatformOnboardingCompleteRoute: typeof ApiPlatformOnboardingCompleteRoute
  ApiPlatformSiweNonceRoute: typeof ApiPlatformSiweNonceRoute
  ApiPlatformWaitlistRoute: typeof ApiPlatformWaitlistRoute
  ApiPulseFeedRoute: typeof ApiPulseFeedRouteWithChildren
  ApiPulseMetricsRoute: typeof ApiPulseMetricsRoute
  ApiRewardsSummaryRoute: typeof ApiRewardsSummaryRoute
  ApiWalletSyncRoute: typeof ApiWalletSyncRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWorldWalletNonceRoute: typeof ApiWorldWalletNonceRoute
  ApiWorldWalletVerifyRoute: typeof ApiWorldWalletVerifyRoute
  ApiX402PremiumRoute: typeof ApiX402PremiumRoute
  ApiPulseAttestationLatestRoute: typeof ApiPulseAttestationLatestRoute
  ApiPulseDigestDayIdRoute: typeof ApiPulseDigestDayIdRoute
  ApiPulseIngestManualRoute: typeof ApiPulseIngestManualRoute
  ApiWalletPacksCheckoutRoute: typeof ApiWalletPacksCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presale': {
      id: '/presale'
      path: '/presale'
      fullPath: '/presale'
      preLoaderRoute: typeof PresaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genesis-district': {
      id: '/genesis-district'
      path: '/genesis-district'
      fullPath: '/genesis-district'
      preLoaderRoute: typeof GenesisDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elias': {
      id: '/elias'
      path: '/elias'
      fullPath: '/elias'
      preLoaderRoute: typeof EliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbase': {
      id: '/chatbase'
      path: '/chatbase'
      fullPath: '/chatbase'
      preLoaderRoute: typeof ChatbaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-fleet': {
      id: '/agent-fleet'
      path: '/agent-fleet'
      fullPath: '/agent-fleet'
      preLoaderRoute: typeof AgentFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/': {
      id: '/signal/'
      path: '/signal'
      fullPath: '/signal/'
      preLoaderRoute: typeof SignalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass/': {
      id: '/pass/'
      path: '/pass'
      fullPath: '/pass/'
      preLoaderRoute: typeof PassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/forest/': {
      id: '/forest/'
      path: '/forest'
      fullPath: '/forest/'
      preLoaderRoute: typeof ForestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earth/': {
      id: '/earth/'
      path: '/earth'
      fullPath: '/earth/'
      preLoaderRoute: typeof EarthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/packs': {
      id: '/wallet/packs'
      path: '/wallet/packs'
      fullPath: '/wallet/packs'
      preLoaderRoute: typeof WalletPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self/agentid': {
      id: '/self/agentid'
      path: '/self/agentid'
      fullPath: '/self/agentid'
      preLoaderRoute: typeof SelfAgentidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$name': {
      id: '/n/$name'
      path: '/n/$name'
      fullPath: '/n/$name'
      preLoaderRoute: typeof NNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/sell': {
      id: '/marketplace/sell'
      path: '/sell'
      fullPath: '/marketplace/sell'
      preLoaderRoute: typeof MarketplaceSellRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/id/$name': {
      id: '/id/$name'
      path: '/id/$name'
      fullPath: '/id/$name'
      preLoaderRoute: typeof IdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forest/quests': {
      id: '/forest/quests'
      path: '/forest/quests'
      fullPath: '/forest/quests'
      preLoaderRoute: typeof ForestQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops/art': {
      id: '/drops/art'
      path: '/drops/art'
      fullPath: '/drops/art'
      preLoaderRoute: typeof DropsArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops/$slug': {
      id: '/drops/$slug'
      path: '/drops/$slug'
      fullPath: '/drops/$slug'
      preLoaderRoute: typeof DropsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/0g/agentid': {
      id: '/0g/agentid'
      path: '/0g/agentid'
      fullPath: '/0g/agentid'
      preLoaderRoute: typeof R0gAgentidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/farcaster.json': {
      id: '/.well-known/farcaster.json'
      path: '/.well-known/farcaster.json'
      fullPath: '/.well-known/farcaster.json'
      preLoaderRoute: typeof DotwellKnownFarcasterDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/premium': {
      id: '/api/x402/premium'
      path: '/api/x402/premium'
      fullPath: '/api/x402/premium'
      preLoaderRoute: typeof ApiX402PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world/wallet-verify': {
      id: '/api/world/wallet-verify'
      path: '/api/world/wallet-verify'
      fullPath: '/api/world/wallet-verify'
      preLoaderRoute: typeof ApiWorldWalletVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world/wallet-nonce': {
      id: '/api/world/wallet-nonce'
      path: '/api/world/wallet-nonce'
      fullPath: '/api/world/wallet-nonce'
      preLoaderRoute: typeof ApiWorldWalletNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/sync': {
      id: '/api/wallet/sync'
      path: '/api/wallet/sync'
      fullPath: '/api/wallet/sync'
      preLoaderRoute: typeof ApiWalletSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewards/summary': {
      id: '/api/rewards/summary'
      path: '/api/rewards/summary'
      fullPath: '/api/rewards/summary'
      preLoaderRoute: typeof ApiRewardsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse/metrics': {
      id: '/api/pulse/metrics'
      path: '/api/pulse/metrics'
      fullPath: '/api/pulse/metrics'
      preLoaderRoute: typeof ApiPulseMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse/feed': {
      id: '/api/pulse/feed'
      path: '/api/pulse/feed'
      fullPath: '/api/pulse/feed'
      preLoaderRoute: typeof ApiPulseFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/waitlist': {
      id: '/api/platform/waitlist'
      path: '/api/platform/waitlist'
      fullPath: '/api/platform/waitlist'
      preLoaderRoute: typeof ApiPlatformWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/siwe-nonce': {
      id: '/api/platform/siwe-nonce'
      path: '/api/platform/siwe-nonce'
      fullPath: '/api/platform/siwe-nonce'
      preLoaderRoute: typeof ApiPlatformSiweNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/onboarding-complete': {
      id: '/api/platform/onboarding-complete'
      path: '/api/platform/onboarding-complete'
      fullPath: '/api/platform/onboarding-complete'
      preLoaderRoute: typeof ApiPlatformOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/analytics': {
      id: '/api/platform/analytics'
      path: '/api/platform/analytics'
      fullPath: '/api/platform/analytics'
      preLoaderRoute: typeof ApiPlatformAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/member/me': {
      id: '/api/member/me'
      path: '/api/member/me'
      fullPath: '/api/member/me'
      preLoaderRoute: typeof ApiMemberMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/x-post': {
      id: '/api/marketing/x-post'
      path: '/api/marketing/x-post'
      fullPath: '/api/marketing/x-post'
      preLoaderRoute: typeof ApiMarketingXPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/identity/verify-name': {
      id: '/api/identity/verify-name'
      path: '/api/identity/verify-name'
      fullPath: '/api/identity/verify-name'
      preLoaderRoute: typeof ApiIdentityVerifyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/identity/resolve': {
      id: '/api/identity/resolve'
      path: '/api/identity/resolve'
      fullPath: '/api/identity/resolve'
      preLoaderRoute: typeof ApiIdentityResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elias/inbound': {
      id: '/api/elias/inbound'
      path: '/api/elias/inbound'
      fullPath: '/api/elias/inbound'
      preLoaderRoute: typeof ApiEliasInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance/eligibility': {
      id: '/api/compliance/eligibility'
      path: '/api/compliance/eligibility'
      fullPath: '/api/compliance/eligibility'
      preLoaderRoute: typeof ApiComplianceEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/status': {
      id: '/api/agents/status'
      path: '/api/agents/status'
      fullPath: '/api/agents/status'
      preLoaderRoute: typeof ApiAgentsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity/log': {
      id: '/api/activity/log'
      path: '/api/activity/log'
      fullPath: '/api/activity/log'
      preLoaderRoute: typeof ApiActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/packs/checkout': {
      id: '/api/wallet/packs/checkout'
      path: '/api/wallet/packs/checkout'
      fullPath: '/api/wallet/packs/checkout'
      preLoaderRoute: typeof ApiWalletPacksCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse/ingest/manual': {
      id: '/api/pulse/ingest/manual'
      path: '/api/pulse/ingest/manual'
      fullPath: '/api/pulse/ingest/manual'
      preLoaderRoute: typeof ApiPulseIngestManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse/digest/$dayId': {
      id: '/api/pulse/digest/$dayId'
      path: '/api/pulse/digest/$dayId'
      fullPath: '/api/pulse/digest/$dayId'
      preLoaderRoute: typeof ApiPulseDigestDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse/attestation/latest': {
      id: '/api/pulse/attestation/latest'
      path: '/api/pulse/attestation/latest'
      fullPath: '/api/pulse/attestation/latest'
      preLoaderRoute: typeof ApiPulseAttestationLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse/feed/$id/comments': {
      id: '/api/pulse/feed/$id/comments'
      path: '/$id/comments'
      fullPath: '/api/pulse/feed/$id/comments'
      preLoaderRoute: typeof ApiPulseFeedIdCommentsRouteImport
      parentRoute: typeof ApiPulseFeedRoute
    }
  }
}

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  MarketplaceSellRoute: typeof MarketplaceSellRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  MarketplaceSellRoute: MarketplaceSellRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ApiPulseFeedRouteChildren {
  ApiPulseFeedIdCommentsRoute: typeof ApiPulseFeedIdCommentsRoute
}

const ApiPulseFeedRouteChildren: ApiPulseFeedRouteChildren = {
  ApiPulseFeedIdCommentsRoute: ApiPulseFeedIdCommentsRoute,
}

const ApiPulseFeedRouteWithChildren = ApiPulseFeedRoute._addFileChildren(
  ApiPulseFeedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentFleetRoute: AgentFleetRoute,
  CampaignRoute: CampaignRoute,
  ChatbaseRoute: ChatbaseRoute,
  CollectionsRoute: CollectionsRoute,
  EliasRoute: EliasRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  GenesisDistrictRoute: GenesisDistrictRoute,
  GuideRoute: GuideRoute,
  InvestorsRoute: InvestorsRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  LegalRoute: LegalRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MissionRoute: MissionRoute,
  PlayRoute: PlayRoute,
  PresaleRoute: PresaleRoute,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownFarcasterDotjsonRoute: DotwellKnownFarcasterDotjsonRoute,
  R0gAgentidRoute: R0gAgentidRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsSlugRoute: DocsSlugRoute,
  DropsSlugRoute: DropsSlugRoute,
  DropsArtRoute: DropsArtRoute,
  ForestQuestsRoute: ForestQuestsRoute,
  IdNameRoute: IdNameRoute,
  NNameRoute: NNameRoute,
  PSlugRoute: PSlugRoute,
  SelfAgentidRoute: SelfAgentidRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  WalletPacksRoute: WalletPacksRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  EarthIndexRoute: EarthIndexRoute,
  ForestIndexRoute: ForestIndexRoute,
  PassIndexRoute: PassIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  SignalIndexRoute: SignalIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
  ApiActivityLogRoute: ApiActivityLogRoute,
  ApiAgentsStatusRoute: ApiAgentsStatusRoute,
  ApiComplianceEligibilityRoute: ApiComplianceEligibilityRoute,
  ApiEliasInboundRoute: ApiEliasInboundRoute,
  ApiIdentityResolveRoute: ApiIdentityResolveRoute,
  ApiIdentityVerifyNameRoute: ApiIdentityVerifyNameRoute,
  ApiMarketingXPostRoute: ApiMarketingXPostRoute,
  ApiMemberMeRoute: ApiMemberMeRoute,
  ApiPlatformAnalyticsRoute: ApiPlatformAnalyticsRoute,
  ApiPlatformOnboardingCompleteRoute: ApiPlatformOnboardingCompleteRoute,
  ApiPlatformSiweNonceRoute: ApiPlatformSiweNonceRoute,
  ApiPlatformWaitlistRoute: ApiPlatformWaitlistRoute,
  ApiPulseFeedRoute: ApiPulseFeedRouteWithChildren,
  ApiPulseMetricsRoute: ApiPulseMetricsRoute,
  ApiRewardsSummaryRoute: ApiRewardsSummaryRoute,
  ApiWalletSyncRoute: ApiWalletSyncRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWorldWalletNonceRoute: ApiWorldWalletNonceRoute,
  ApiWorldWalletVerifyRoute: ApiWorldWalletVerifyRoute,
  ApiX402PremiumRoute: ApiX402PremiumRoute,
  ApiPulseAttestationLatestRoute: ApiPulseAttestationLatestRoute,
  ApiPulseDigestDayIdRoute: ApiPulseDigestDayIdRoute,
  ApiPulseIngestManualRoute: ApiPulseIngestManualRoute,
  ApiWalletPacksCheckoutRoute: ApiWalletPacksCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
