/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MintRouteImport } from './routes/mint'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdNameRouteImport } from './routes/id.$name'
import { Route as ApiSocialAddressRouteImport } from './routes/api/social/$address'
import { Route as ApiNftTokenIdRouteImport } from './routes/api/nft/$tokenId'
import { Route as ApiMiniProfileRouteImport } from './routes/api/mini/profile'
import { Route as ApiMiniMeRouteImport } from './routes/api/mini/me'
import { Route as ApiMiniLeaderboardRouteImport } from './routes/api/mini/leaderboard'
import { Route as ApiNftTokenIdImageRouteImport } from './routes/api/nft/$tokenId/image'
import { Route as ApiMiniTasksTaskIdVerifyRouteImport } from './routes/api/mini/tasks/$taskId/verify'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdNameRoute = IdNameRouteImport.update({
  id: '/id/$name',
  path: '/id/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialAddressRoute = ApiSocialAddressRouteImport.update({
  id: '/api/social/$address',
  path: '/api/social/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNftTokenIdRoute = ApiNftTokenIdRouteImport.update({
  id: '/api/nft/$tokenId',
  path: '/api/nft/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiniProfileRoute = ApiMiniProfileRouteImport.update({
  id: '/api/mini/profile',
  path: '/api/mini/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiniMeRoute = ApiMiniMeRouteImport.update({
  id: '/api/mini/me',
  path: '/api/mini/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiniLeaderboardRoute = ApiMiniLeaderboardRouteImport.update({
  id: '/api/mini/leaderboard',
  path: '/api/mini/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNftTokenIdImageRoute = ApiNftTokenIdImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiNftTokenIdRoute,
} as any)
const ApiMiniTasksTaskIdVerifyRoute =
  ApiMiniTasksTaskIdVerifyRouteImport.update({
    id: '/api/mini/tasks/$taskId/verify',
    path: '/api/mini/tasks/$taskId/verify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mint': typeof MintRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/id/$name': typeof IdNameRoute
  '/api/mini/leaderboard': typeof ApiMiniLeaderboardRoute
  '/api/mini/me': typeof ApiMiniMeRoute
  '/api/mini/profile': typeof ApiMiniProfileRoute
  '/api/nft/$tokenId': typeof ApiNftTokenIdRouteWithChildren
  '/api/social/$address': typeof ApiSocialAddressRoute
  '/api/nft/$tokenId/image': typeof ApiNftTokenIdImageRoute
  '/api/mini/tasks/$taskId/verify': typeof ApiMiniTasksTaskIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mint': typeof MintRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/id/$name': typeof IdNameRoute
  '/api/mini/leaderboard': typeof ApiMiniLeaderboardRoute
  '/api/mini/me': typeof ApiMiniMeRoute
  '/api/mini/profile': typeof ApiMiniProfileRoute
  '/api/nft/$tokenId': typeof ApiNftTokenIdRouteWithChildren
  '/api/social/$address': typeof ApiSocialAddressRoute
  '/api/nft/$tokenId/image': typeof ApiNftTokenIdImageRoute
  '/api/mini/tasks/$taskId/verify': typeof ApiMiniTasksTaskIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mint': typeof MintRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/id/$name': typeof IdNameRoute
  '/api/mini/leaderboard': typeof ApiMiniLeaderboardRoute
  '/api/mini/me': typeof ApiMiniMeRoute
  '/api/mini/profile': typeof ApiMiniProfileRoute
  '/api/nft/$tokenId': typeof ApiNftTokenIdRouteWithChildren
  '/api/social/$address': typeof ApiSocialAddressRoute
  '/api/nft/$tokenId/image': typeof ApiNftTokenIdImageRoute
  '/api/mini/tasks/$taskId/verify': typeof ApiMiniTasksTaskIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/mint'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/tasks'
    | '/terms'
    | '/id/$name'
    | '/api/mini/leaderboard'
    | '/api/mini/me'
    | '/api/mini/profile'
    | '/api/nft/$tokenId'
    | '/api/social/$address'
    | '/api/nft/$tokenId/image'
    | '/api/mini/tasks/$taskId/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/mint'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/tasks'
    | '/terms'
    | '/id/$name'
    | '/api/mini/leaderboard'
    | '/api/mini/me'
    | '/api/mini/profile'
    | '/api/nft/$tokenId'
    | '/api/social/$address'
    | '/api/nft/$tokenId/image'
    | '/api/mini/tasks/$taskId/verify'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/mint'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/tasks'
    | '/terms'
    | '/id/$name'
    | '/api/mini/leaderboard'
    | '/api/mini/me'
    | '/api/mini/profile'
    | '/api/nft/$tokenId'
    | '/api/social/$address'
    | '/api/nft/$tokenId/image'
    | '/api/mini/tasks/$taskId/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MintRoute: typeof MintRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  IdNameRoute: typeof IdNameRoute
  ApiMiniLeaderboardRoute: typeof ApiMiniLeaderboardRoute
  ApiMiniMeRoute: typeof ApiMiniMeRoute
  ApiMiniProfileRoute: typeof ApiMiniProfileRoute
  ApiNftTokenIdRoute: typeof ApiNftTokenIdRouteWithChildren
  ApiSocialAddressRoute: typeof ApiSocialAddressRoute
  ApiMiniTasksTaskIdVerifyRoute: typeof ApiMiniTasksTaskIdVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id/$name': {
      id: '/id/$name'
      path: '/id/$name'
      fullPath: '/id/$name'
      preLoaderRoute: typeof IdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/$address': {
      id: '/api/social/$address'
      path: '/api/social/$address'
      fullPath: '/api/social/$address'
      preLoaderRoute: typeof ApiSocialAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nft/$tokenId': {
      id: '/api/nft/$tokenId'
      path: '/api/nft/$tokenId'
      fullPath: '/api/nft/$tokenId'
      preLoaderRoute: typeof ApiNftTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mini/profile': {
      id: '/api/mini/profile'
      path: '/api/mini/profile'
      fullPath: '/api/mini/profile'
      preLoaderRoute: typeof ApiMiniProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mini/me': {
      id: '/api/mini/me'
      path: '/api/mini/me'
      fullPath: '/api/mini/me'
      preLoaderRoute: typeof ApiMiniMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mini/leaderboard': {
      id: '/api/mini/leaderboard'
      path: '/api/mini/leaderboard'
      fullPath: '/api/mini/leaderboard'
      preLoaderRoute: typeof ApiMiniLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nft/$tokenId/image': {
      id: '/api/nft/$tokenId/image'
      path: '/image'
      fullPath: '/api/nft/$tokenId/image'
      preLoaderRoute: typeof ApiNftTokenIdImageRouteImport
      parentRoute: typeof ApiNftTokenIdRoute
    }
    '/api/mini/tasks/$taskId/verify': {
      id: '/api/mini/tasks/$taskId/verify'
      path: '/api/mini/tasks/$taskId/verify'
      fullPath: '/api/mini/tasks/$taskId/verify'
      preLoaderRoute: typeof ApiMiniTasksTaskIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiNftTokenIdRouteChildren {
  ApiNftTokenIdImageRoute: typeof ApiNftTokenIdImageRoute
}

const ApiNftTokenIdRouteChildren: ApiNftTokenIdRouteChildren = {
  ApiNftTokenIdImageRoute: ApiNftTokenIdImageRoute,
}

const ApiNftTokenIdRouteWithChildren = ApiNftTokenIdRoute._addFileChildren(
  ApiNftTokenIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MintRoute: MintRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  IdNameRoute: IdNameRoute,
  ApiMiniLeaderboardRoute: ApiMiniLeaderboardRoute,
  ApiMiniMeRoute: ApiMiniMeRoute,
  ApiMiniProfileRoute: ApiMiniProfileRoute,
  ApiNftTokenIdRoute: ApiNftTokenIdRouteWithChildren,
  ApiSocialAddressRoute: ApiSocialAddressRoute,
  ApiMiniTasksTaskIdVerifyRoute: ApiMiniTasksTaskIdVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
