/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTranslateRouteImport } from './routes/app.translate'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppSchoolsRouteImport } from './routes/app.schools'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppHousingRouteImport } from './routes/app.housing'
import { Route as AppHealthcareRouteImport } from './routes/app.healthcare'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppBenefitsRouteImport } from './routes/app.benefits'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTranslateRoute = AppTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolsRoute = AppSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHousingRoute = AppHousingRouteImport.update({
  id: '/housing',
  path: '/housing',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthcareRoute = AppHealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppBenefitsRoute = AppBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/benefits': typeof AppBenefitsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/healthcare': typeof AppHealthcareRoute
  '/app/housing': typeof AppHousingRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/translate': typeof AppTranslateRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/benefits': typeof AppBenefitsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/healthcare': typeof AppHealthcareRoute
  '/app/housing': typeof AppHousingRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/translate': typeof AppTranslateRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/benefits': typeof AppBenefitsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/healthcare': typeof AppHealthcareRoute
  '/app/housing': typeof AppHousingRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/translate': typeof AppTranslateRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/documents'
    | '/app/healthcare'
    | '/app/housing'
    | '/app/jobs'
    | '/app/profile'
    | '/app/schools'
    | '/app/services'
    | '/app/settings'
    | '/app/translate'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/documents'
    | '/app/healthcare'
    | '/app/housing'
    | '/app/jobs'
    | '/app/profile'
    | '/app/schools'
    | '/app/services'
    | '/app/settings'
    | '/app/translate'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/documents'
    | '/app/healthcare'
    | '/app/housing'
    | '/app/jobs'
    | '/app/profile'
    | '/app/schools'
    | '/app/services'
    | '/app/settings'
    | '/app/translate'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/translate': {
      id: '/app/translate'
      path: '/translate'
      fullPath: '/app/translate'
      preLoaderRoute: typeof AppTranslateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schools': {
      id: '/app/schools'
      path: '/schools'
      fullPath: '/app/schools'
      preLoaderRoute: typeof AppSchoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/housing': {
      id: '/app/housing'
      path: '/housing'
      fullPath: '/app/housing'
      preLoaderRoute: typeof AppHousingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/healthcare': {
      id: '/app/healthcare'
      path: '/healthcare'
      fullPath: '/app/healthcare'
      preLoaderRoute: typeof AppHealthcareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/benefits': {
      id: '/app/benefits'
      path: '/benefits'
      fullPath: '/app/benefits'
      preLoaderRoute: typeof AppBenefitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppBenefitsRoute: typeof AppBenefitsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHealthcareRoute: typeof AppHealthcareRoute
  AppHousingRoute: typeof AppHousingRoute
  AppJobsRoute: typeof AppJobsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSchoolsRoute: typeof AppSchoolsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTranslateRoute: typeof AppTranslateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppBenefitsRoute: AppBenefitsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHealthcareRoute: AppHealthcareRoute,
  AppHousingRoute: AppHousingRoute,
  AppJobsRoute: AppJobsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSchoolsRoute: AppSchoolsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTranslateRoute: AppTranslateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
