/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PathsSlugRouteImport } from './routes/paths.$slug'
import { Route as MembersProgressRouteImport } from './routes/members/progress'
import { Route as MembersPartnerRouteImport } from './routes/members/partner'
import { Route as MembersMoodRouteImport } from './routes/members/mood'
import { Route as MembersLibraryRouteImport } from './routes/members/library'
import { Route as MembersJournalRouteImport } from './routes/members/journal'
import { Route as JoinSuccessRouteImport } from './routes/join/success'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppMissionsRouteImport } from './routes/app/missions'
import { Route as AppAchievementsRouteImport } from './routes/app/achievements'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/paths/$slug',
  path: '/paths/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersProgressRoute = MembersProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => MembersRoute,
} as any)
const MembersPartnerRoute = MembersPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => MembersRoute,
} as any)
const MembersMoodRoute = MembersMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => MembersRoute,
} as any)
const MembersLibraryRoute = MembersLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MembersRoute,
} as any)
const MembersJournalRoute = MembersJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => MembersRoute,
} as any)
const JoinSuccessRoute = JoinSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => JoinRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/story': typeof StoryRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/join/success': typeof JoinSuccessRoute
  '/members/journal': typeof MembersJournalRoute
  '/members/library': typeof MembersLibraryRoute
  '/members/mood': typeof MembersMoodRoute
  '/members/partner': typeof MembersPartnerRoute
  '/members/progress': typeof MembersProgressRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/app/': typeof AppIndexRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/story': typeof StoryRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/join/success': typeof JoinSuccessRoute
  '/members/journal': typeof MembersJournalRoute
  '/members/library': typeof MembersLibraryRoute
  '/members/mood': typeof MembersMoodRoute
  '/members/partner': typeof MembersPartnerRoute
  '/members/progress': typeof MembersProgressRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/app': typeof AppIndexRoute
  '/members': typeof MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/story': typeof StoryRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/join/success': typeof JoinSuccessRoute
  '/members/journal': typeof MembersJournalRoute
  '/members/library': typeof MembersLibraryRoute
  '/members/mood': typeof MembersMoodRoute
  '/members/partner': typeof MembersPartnerRoute
  '/members/progress': typeof MembersProgressRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/app/': typeof AppIndexRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/join'
    | '/login'
    | '/members'
    | '/story'
    | '/app/achievements'
    | '/app/missions'
    | '/app/profile'
    | '/join/success'
    | '/members/journal'
    | '/members/library'
    | '/members/mood'
    | '/members/partner'
    | '/members/progress'
    | '/paths/$slug'
    | '/app/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/story'
    | '/app/achievements'
    | '/app/missions'
    | '/app/profile'
    | '/join/success'
    | '/members/journal'
    | '/members/library'
    | '/members/mood'
    | '/members/partner'
    | '/members/progress'
    | '/paths/$slug'
    | '/app'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/join'
    | '/login'
    | '/members'
    | '/story'
    | '/app/achievements'
    | '/app/missions'
    | '/app/profile'
    | '/join/success'
    | '/members/journal'
    | '/members/library'
    | '/members/mood'
    | '/members/partner'
    | '/members/progress'
    | '/paths/$slug'
    | '/app/'
    | '/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  StoryRoute: typeof StoryRoute
  PathsSlugRoute: typeof PathsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/paths/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/progress': {
      id: '/members/progress'
      path: '/progress'
      fullPath: '/members/progress'
      preLoaderRoute: typeof MembersProgressRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/partner': {
      id: '/members/partner'
      path: '/partner'
      fullPath: '/members/partner'
      preLoaderRoute: typeof MembersPartnerRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/mood': {
      id: '/members/mood'
      path: '/mood'
      fullPath: '/members/mood'
      preLoaderRoute: typeof MembersMoodRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/library': {
      id: '/members/library'
      path: '/library'
      fullPath: '/members/library'
      preLoaderRoute: typeof MembersLibraryRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/journal': {
      id: '/members/journal'
      path: '/journal'
      fullPath: '/members/journal'
      preLoaderRoute: typeof MembersJournalRouteImport
      parentRoute: typeof MembersRoute
    }
    '/join/success': {
      id: '/join/success'
      path: '/success'
      fullPath: '/join/success'
      preLoaderRoute: typeof JoinSuccessRouteImport
      parentRoute: typeof JoinRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions': {
      id: '/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface JoinRouteChildren {
  JoinSuccessRoute: typeof JoinSuccessRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinSuccessRoute: JoinSuccessRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

interface MembersRouteChildren {
  MembersJournalRoute: typeof MembersJournalRoute
  MembersLibraryRoute: typeof MembersLibraryRoute
  MembersMoodRoute: typeof MembersMoodRoute
  MembersPartnerRoute: typeof MembersPartnerRoute
  MembersProgressRoute: typeof MembersProgressRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersJournalRoute: MembersJournalRoute,
  MembersLibraryRoute: MembersLibraryRoute,
  MembersMoodRoute: MembersMoodRoute,
  MembersPartnerRoute: MembersPartnerRoute,
  MembersProgressRoute: MembersProgressRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRouteWithChildren,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  StoryRoute: StoryRoute,
  PathsSlugRoute: PathsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
