#!/usr/bin/env bash
# Deploy bootstrap agents to production: web + Grove timer + bc-agent-tick (15m).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_ENV="$ROOT/deploy/.env"
HOST="${DEPLOY_HOST:-root@187.124.18.204}"
REMOTE_DIR="${DEPLOY_PATH:-/opt/buildingculture-frontend}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519_wgsdex}"
SSH_OPTS=( -i "$SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes -o ServerAliveInterval=30 )

[[ -f "$DEPLOY_ENV" ]] || { echo "missing deploy/.env"; exit 1; }

echo "==> Ensure bootstrap env locally"
grep -q '^AGENT_BOOTSTRAP_MODE=1' "$DEPLOY_ENV" || {
  bash "$ROOT/scripts/bootstrap-agents-live.sh" || true
}

echo "==> Deploy web + Grove (deploy-grove.sh)"
DEPLOY_HOST="$HOST" DEPLOY_PATH="$REMOTE_DIR" SSH_KEY="$SSH_KEY" \
  bash "$ROOT/scripts/deploy-grove.sh"

echo "==> Push deploy/.env → server app/.env (rsync excludes app/.env)"
rsync -avz \
  -e "ssh ${SSH_OPTS[*]}" \
  "$DEPLOY_ENV" "$HOST:$REMOTE_DIR/app/.env"

echo "==> Sync ops/ + agent packages"
rsync -avz \
  -e "ssh ${SSH_OPTS[*]}" \
  "$ROOT/ops/" "$HOST:$REMOTE_DIR/ops/"

echo "==> Remote: build agent-runtime + install bc-agent-tick timer"
ssh "${SSH_OPTS[@]}" "$HOST" bash -s -- "$REMOTE_DIR" <<'REMOTE'
set -euo pipefail
RDIR="$1"
cd "$RDIR"

npm install --no-audit --no-fund --workspace @bc/bcd-orchestration --workspace @bc/agent-runtime 2>/dev/null \
  || npm install --no-audit --no-fund
npm run build -w @bc/bcd-orchestration -w @bc/agent-runtime

ENV_FILE="$RDIR/app/.env"
TICK_ENV=/etc/bc-agent-tick.env

# Host-side DATABASE_URL (Postgres bound to 127.0.0.1:5433 on VPS)
DB_URL="$(grep '^DATABASE_URL=' "$ENV_FILE" | cut -d= -f2- | sed 's/@postgres:5432/@127.0.0.1:5433/')"

{
  echo "# bc-agent-tick — generated by deploy-bootstrap-live.sh"
  echo "DATABASE_URL=${DB_URL}"
  grep -E '^(AGENTS_PAUSED|ECON_LIVE|AGENT_BOOTSTRAP_MODE|AGENT_LLM_PROVIDER|AGENT_LLM_ALLOW_OPENAI_FALLBACK|AGENT_LLM_MODEL|OPENAI_API_KEY|AGENT_LLM_API_KEY|GROVE_LLM_ENABLED|SLACK_WEBHOOK_URL|AGENT_SLACK_WEBHOOK_URL|AGENT_BASE_RPC_URL|BASE_RPC_URL|AGENT_CHAIN_ID|PUBLIC_APP_ORIGIN|VITE_PUBLIC_APP_ORIGIN|X402_PRICE|STRAPI_URL|STRAPI_API_TOKEN|AGENT_STRAPI)=' "$ENV_FILE" 2>/dev/null || true
} > /tmp/bc-agent-tick.env.new
mv /tmp/bc-agent-tick.env.new "$TICK_ENV"
chmod 600 "$TICK_ENV"

cat > /etc/systemd/system/bc-agent-tick.service <<EOF
[Unit]
Description=Building Culture agent runtime tick
After=network-online.target docker.service

[Service]
Type=oneshot
WorkingDirectory=${RDIR}
EnvironmentFile=${TICK_ENV}
ExecStart=/usr/bin/env bash -lc 'cd ${RDIR} && node packages/agent-runtime/dist/cli/run-tick.js --agent all --config ${RDIR}/ops/agents.json'
EOF

cat > /etc/systemd/system/bc-agent-tick.timer <<'EOF'
[Unit]
Description=Run bc-agent-tick every 15 minutes

[Timer]
OnBootSec=3min
OnUnitActiveSec=15min
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable bc-agent-tick.timer
systemctl restart bc-agent-tick.timer

echo "==> prisma migrate deploy (agent orchestration tables)"
docker exec buildingculture-web-1 npx prisma migrate deploy 2>/dev/null || echo "warn: migrate skipped — run manually if web container down"

systemctl start bc-agent-tick.service || true
echo "bc-agent-tick timer: $(systemctl is-active bc-agent-tick.timer)"
REMOTE

echo "==> Production smoke"
curl -sS -o /dev/null -w "app: %{http_code}\n" "https://app.buildingcultureid.space/agent-fleet" || true
curl -sS "https://app.buildingcultureid.space/api/marketing/grove/tick" | head -c 200 || true
echo ""
echo "==> Done. Fund OpenAI billing, then: systemctl start bc-agent-tick.service on server to test."
